services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports: 
     - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres

  frontend:
    build: ./frontend
    ports: 
     - "3001:3001"
    depends_on:
      - backend
    links:
      - backend
volumes:
  db:
